# Generated by Django 4.0 on 2023-04-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_like_alter_room_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='like',
        ),
    ]
