# Generated by Django 4.1.7 on 2023-03-04 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='categories',
            new_name='category',
        ),
    ]
