# Generated by Django 4.0 on 2023-04-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_remove_room_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
