databases:
  - name: airbnbclone
    databaseName: airbnbclone
    user: airbnbclone
    region: singapore # render의 아시아 서버는 singpore에 있음

services:
  - type: web
    name: airbnbclone
    env: python
    region: singapore #
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application" # python3 manage.py runserver 명령이 아닌 gunicorn 사용
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: airbnbclone
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4