# Generated by Django 4.1.7 on 2023-03-04 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_experience_categories_alter_perk_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='categories',
            new_name='category',
        ),
    ]
