# Generated by Django 4.1.7 on 2023-03-04 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='users',
            new_name='user',
        ),
    ]
