# Generated by Django 4.1.7 on 2023-04-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_not_canceled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='not_canceled',
        ),
        migrations.AddField(
            model_name='booking',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
